import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Quicksand } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-quicksand",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
